
#ifndef NEAR_PASS_DETECTOR_PARAMS_H
#define NEAR_PASS_DETECTOR_PARAMS_H

const int DISTANCE_THRESHOLD_cm = 200;

const int NEAR_PASS_MIN_DURATION_ms = 100;
const int NEAR_PASS_MAX_DURATION_ms = 5000;

const int NEAR_PASS_STABILITY_DURATION_ms = 100;

const int NEAR_PASS_COOLDOWN_ms = 300;

#endif